version: '3'

services: 
    php:
        container_name: php
        build: ./docker/php
        volumes:
            - ${SOURCE_PATH:-./src}:/var/www/html
    composer:
        container_name: composer
        build: ./docker/composer
        volumes:
            - ${SOURCE_PATH:-./src}:/src