version: '3'

services: 
    php:
        container_name: php
        build: ./docker/php
        volumes:
            - ${SOURCE_PATH:-./src}:/var/www/html
    composer:
        container_name: composer
        build: ./docker/composer
        volumes:
            - ${SOURCE_PATH:-./src}:/src
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            TZ: ${DB_TZ}
        volumes:
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
        ports:
            - 3306:3306