version: '3'

services: 
    php:
        container_name: php
        build: ./docker/php
        volumes:
            - ${SOURCE_PATH:-./src}:/var/www/html/
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
        environment: 
            - TZ=${TZ}
    composer:
        container_name: composer
        build: ./docker/composer
        volumes:
            - ${SOURCE_PATH:-./src}:/src
    node:
        container_name: node 
        build: ./docker/node
        volumes:
            - ${SOURCE_PATH:-./src}:/src
    db:
        image: mysql:5.7
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
            MYSQL_DATABASE: ${DB_NAME}
            MYSQL_USER: ${DB_USER}
            MYSQL_PASSWORD: ${DB_PASS}
            TZ: ${TZ}
        volumes:
            - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    nginx:
        image: nginx:1.17
        container_name: nginx
        depends_on: 
            - php
        volumes:
            - ./src:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80